apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: barn
data:
  blobstore.conf: |
    content_addressable_storage {
      redis {
        endpoint: "redis:6379"
        db: 0
      }
    }
    action_cache {
      redis {
        endpoint: "redis:6379"
        db: 1
      }
    }
