apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: grid
spec:
  replicas: 16
  template:
    metadata:
      labels:
        k8s-app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/stack-build/buildkube/grid/worker:latest
        args:
        - bot
        - --remote=http://server:8980
        - --parent=main
        - host-tools
