apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildfarm-server
  labels:
    k8s-app: buildfarm-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: buildfarm-server
    spec:
      containers:
      - name: buildfarm-server
        image: gcr.io/stack-build/buildfarm-server:latest
        ports:
        - containerPort: 8980
          name: grpc
