apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  labels:
    k8s-app: server
  namespace: grid
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: server
    spec:
      containers:
      - name: server
        image: gcr.io/stack-build/buildkube/grid/server:latest
        ports:
        - containerPort: 8980