apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: farm
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: worker
    spec:
      containers:
      - name: worker
        image: gcr.io/stack-build/buildkube/farm/worker:latest