apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildkube-server
  labels:
    k8s-app: buildkube-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: buildkube-server
    spec:
      containers:
      - name: buildkube-server
        image: gcr.io/stack-build/buildkube-server:latest
        ports:
        - containerPort: 8980
          name: grpc
